{{- $labels := include "docker-registry.labels" . }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
type: {{ .stype }}
data:
  {{- range .data }}
  {{ .name }}: {{ .value }}
  {{- end }}
---
{{- end }}

